import { type Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts ./types/appwrite/`.

export type Users = Models.Document & {
    username: string;
    email: string;
    avatar: string;
    accountId: string;
}

export type Videos = Models.Document & {
    title: string;
    thumbnail: string;
    prompt: string;
    video: string;
    creator: Users;
}
